<?php

namespace Fluentickr\Traits;

/**
 * @property-read \Fluentickr\Method $add
 * @property-read \Fluentickr\Method $addComment
 * @property-read \Fluentickr\Method $addPhoto
 * @property-read \Fluentickr\Method $addTags
 * @property-read \Fluentickr\Method $approveSuggestion
 * @property-read \Fluentickr\Method $batchCorrectLocation
 * @property-read \Fluentickr\Method $browse
 * @property-read \Fluentickr\Method $checkTickets
 * @property-read \Fluentickr\Method $checkToken
 * @property-read \Fluentickr\Method $correctLocation
 * @property-read \Fluentickr\Method $create
 * @property-read \Fluentickr\Method $delete
 * @property-read \Fluentickr\Method $deleteComment
 * @property-read \Fluentickr\Method $deleteCoords
 * @property-read \Fluentickr\Method $echo
 * @property-read \Fluentickr\Method $edit
 * @property-read \Fluentickr\Method $editComment
 * @property-read \Fluentickr\Method $editCoords
 * @property-read \Fluentickr\Method $editMeta
 * @property-read \Fluentickr\Method $editPhoto
 * @property-read \Fluentickr\Method $editPhotos
 * @property-read \Fluentickr\Method $find
 * @property-read \Fluentickr\Method $findByEmail
 * @property-read \Fluentickr\Method $findByLatLon
 * @property-read \Fluentickr\Method $findByUsername
 * @property-read \Fluentickr\Method $getAccessToken
 * @property-read \Fluentickr\Method $getAllContexts
 * @property-read \Fluentickr\Method $getBrandModels
 * @property-read \Fluentickr\Method $getBrands
 * @property-read \Fluentickr\Method $getCSVFiles
 * @property-read \Fluentickr\Method $getChildrenWithPhotosPublic
 * @property-read \Fluentickr\Method $getClusterPhotos
 * @property-read \Fluentickr\Method $getClusters
 * @property-read \Fluentickr\Method $getCollectionDomains
 * @property-read \Fluentickr\Method $getCollectionReferrers
 * @property-read \Fluentickr\Method $getCollectionStats
 * @property-read \Fluentickr\Method $getContactsPhotos
 * @property-read \Fluentickr\Method $getContactsPublicPhotos
 * @property-read \Fluentickr\Method $getContentType
 * @property-read \Fluentickr\Method $getContext
 * @property-read \Fluentickr\Method $getCounts
 * @property-read \Fluentickr\Method $getExif
 * @property-read \Fluentickr\Method $getFavorites
 * @property-read \Fluentickr\Method $getFrob
 * @property-read \Fluentickr\Method $getFullToken
 * @property-read \Fluentickr\Method $getGeoPerms
 * @property-read \Fluentickr\Method $getGroup
 * @property-read \Fluentickr\Method $getGroups
 * @property-read \Fluentickr\Method $getHidden
 * @property-read \Fluentickr\Method $getHotList
 * @property-read \Fluentickr\Method $getInfo
 * @property-read \Fluentickr\Method $getInfoByUrl
 * @property-read \Fluentickr\Method $getInstitutions
 * @property-read \Fluentickr\Method $getLimits
 * @property-read \Fluentickr\Method $getList
 * @property-read \Fluentickr\Method $getListForPhoto
 * @property-read \Fluentickr\Method $getListPhoto
 * @property-read \Fluentickr\Method $getListRecentlyUploaded
 * @property-read \Fluentickr\Method $getListUser
 * @property-read \Fluentickr\Method $getListUserPopular
 * @property-read \Fluentickr\Method $getListUserRaw
 * @property-read \Fluentickr\Method $getLocation
 * @property-read \Fluentickr\Method $getMethodInfo
 * @property-read \Fluentickr\Method $getMethods
 * @property-read \Fluentickr\Method $getMostFrequentlyUsed
 * @property-read \Fluentickr\Method $getNamespaces
 * @property-read \Fluentickr\Method $getNotInSet
 * @property-read \Fluentickr\Method $getPairs
 * @property-read \Fluentickr\Method $getPerms
 * @property-read \Fluentickr\Method $getPhotoDomains
 * @property-read \Fluentickr\Method $getPhotoReferrers
 * @property-read \Fluentickr\Method $getPhotoStats
 * @property-read \Fluentickr\Method $getPhotos
 * @property-read \Fluentickr\Method $getPhotosOf
 * @property-read \Fluentickr\Method $getPhotosetDomains
 * @property-read \Fluentickr\Method $getPhotosetReferrers
 * @property-read \Fluentickr\Method $getPhotosetStats
 * @property-read \Fluentickr\Method $getPhotostreamDomains
 * @property-read \Fluentickr\Method $getPhotostreamReferrers
 * @property-read \Fluentickr\Method $getPhotostreamStats
 * @property-read \Fluentickr\Method $getPlaceTypes
 * @property-read \Fluentickr\Method $getPopularPhotos
 * @property-read \Fluentickr\Method $getPredicates
 * @property-read \Fluentickr\Method $getPrivacy
 * @property-read \Fluentickr\Method $getPublicGroups
 * @property-read \Fluentickr\Method $getPublicList
 * @property-read \Fluentickr\Method $getPublicPhotos
 * @property-read \Fluentickr\Method $getRecent
 * @property-read \Fluentickr\Method $getRecentForContacts
 * @property-read \Fluentickr\Method $getRecentValues
 * @property-read \Fluentickr\Method $getRelated
 * @property-read \Fluentickr\Method $getSafetyLevel
 * @property-read \Fluentickr\Method $getServices
 * @property-read \Fluentickr\Method $getShapeHistory
 * @property-read \Fluentickr\Method $getSizes
 * @property-read \Fluentickr\Method $getSubscriptions
 * @property-read \Fluentickr\Method $getTaggingSuggestions
 * @property-read \Fluentickr\Method $getToken
 * @property-read \Fluentickr\Method $getTopPlacesList
 * @property-read \Fluentickr\Method $getTopics
 * @property-read \Fluentickr\Method $getTotalViews
 * @property-read \Fluentickr\Method $getTree
 * @property-read \Fluentickr\Method $getUntagged
 * @property-read \Fluentickr\Method $getUploadStatus
 * @property-read \Fluentickr\Method $getUserPhotos
 * @property-read \Fluentickr\Method $getUserProfile
 * @property-read \Fluentickr\Method $getValues
 * @property-read \Fluentickr\Method $getWithGeoData
 * @property-read \Fluentickr\Method $getWithoutGeoData
 * @property-read \Fluentickr\Method $join
 * @property-read \Fluentickr\Method $joinRequest
 * @property-read \Fluentickr\Method $leave
 * @property-read \Fluentickr\Method $login
 * @property-read \Fluentickr\Method $lookupGallery
 * @property-read \Fluentickr\Method $lookupGroup
 * @property-read \Fluentickr\Method $lookupUser
 * @property-read \Fluentickr\Method $null
 * @property-read \Fluentickr\Method $orderSets
 * @property-read \Fluentickr\Method $photosForLocation
 * @property-read \Fluentickr\Method $placesForBoundingBox
 * @property-read \Fluentickr\Method $placesForContacts
 * @property-read \Fluentickr\Method $placesForTags
 * @property-read \Fluentickr\Method $placesForUser
 * @property-read \Fluentickr\Method $postPhoto
 * @property-read \Fluentickr\Method $recentlyUpdated
 * @property-read \Fluentickr\Method $rejectSuggestion
 * @property-read \Fluentickr\Method $remove
 * @property-read \Fluentickr\Method $removeLocation
 * @property-read \Fluentickr\Method $removePhoto
 * @property-read \Fluentickr\Method $removePhotos
 * @property-read \Fluentickr\Method $removeSuggestion
 * @property-read \Fluentickr\Method $removeTag
 * @property-read \Fluentickr\Method $reorderPhotos
 * @property-read \Fluentickr\Method $resolvePlaceId
 * @property-read \Fluentickr\Method $resolvePlaceURL
 * @property-read \Fluentickr\Method $rotate
 * @property-read \Fluentickr\Method $search
 * @property-read \Fluentickr\Method $setContentType
 * @property-read \Fluentickr\Method $setContext
 * @property-read \Fluentickr\Method $setDates
 * @property-read \Fluentickr\Method $setLicense
 * @property-read \Fluentickr\Method $setLocation
 * @property-read \Fluentickr\Method $setMeta
 * @property-read \Fluentickr\Method $setPerms
 * @property-read \Fluentickr\Method $setPrimaryPhoto
 * @property-read \Fluentickr\Method $setSafetyLevel
 * @property-read \Fluentickr\Method $setTags
 * @property-read \Fluentickr\Method $subscribe
 * @property-read \Fluentickr\Method $suggestLocation
 * @property-read \Fluentickr\Method $tagsForPlace
 * @property-read \Fluentickr\Method $unsubscribe
 * @property-read \Fluentickr\Method $userComments
 * @property-read \Fluentickr\Method $userPhotos
 */
trait TrailingMethodHintTrait
{

}
